### ISSUE TITLE
[BUG 1.20.2 / Ver. 2.0.0] The offset problem

### ISSUE THREAD

**Issue by OKA-TAi** [KrLite/Verticality#4] opened 2023-10-27 07:02 UTC
In the game, when i switch UI to vertical style, while hotbar and health bar moves to the right and lower respectively and as intended by mod, but all other bars (Including item name one) doesn't do anything, that means hunger bar, breath bar, exp bar, and etc doesn't offsets lower as health bar one does.

**Comment by OKA-TAi** [comment] 2023-10-27 07:13
I'm sorry for my mistake, name bars switching correctly, but all other problems are still present!

I'm linking a images for better showcase of problem i encountered: https://imgur.com/a/Ny695g7

(Mod was been used on Fabric modloader on MC 1.20.2, all mod updates installed)

**Comment by OKA-TAi** [comment] 2023-10-27 07:30
Also applies for a spectator mode, but in this case it's hotbar doesn't even moving (While icons moving as intended)

Additional note: I tried to launch this mod isolated (Means: Without any other mods) - all problems remained as it is

**Comment by KrLite** [comment] 2023-10-27 12:23
Thanks for reporting! I can reproduce the bugs locally in `1.20.2`, but in `1.20.1` or lower I can't. This might caused by some annoying modifications Mojang made to `1.20.2`.
This shouldn't be very hard to fix and I will check this out soon!

**Comment by OKA-TAi** [comment] 2023-10-27 12:37
Well i tried to find any way to contact you for those, but after a some search found only github, will wait for an update, this mod will fit into my personal vanilla modpack as an interesting feature hehe

**Comment by OKA-TAi** [comment] 2023-10-31 09:26
Hello, i just wanted to ask how is it going there, i can't wait to continue use this mod fixed on my client sooner, and sorry if it bothers you, it is not intended ono...

**Comment by KrLite** [comment] 2023-10-31 11:17
> Hello, i just wanted to ask how is it going there, i can't wait to continue use this mod fixed on my client sooner, and sorry if it bothers you, it is not intended ono...

I'm currently a bit busy, but urgent for you, I'll solve this tonight.

**Comment by OKA-TAi** [comment] 2023-10-31 11:29
> .

Don't worry, i can wait easy if you're busy, no need to rush yourself because of me *Pat-pat-pat*

**Comment by KrLite** [comment] 2023-10-31 11:48
New versions out! This issue has been fixed in [`2.0.1`](https://modrinth.com/mod/verticality/version/2.0.1-mc1.20.2). Enjoy your games!

**Closed as completed by KrLite** 2023-10-31 11:48 UTC
